### ISSUE TITLE
YunoHost container changes host's hostname

### ISSUE THREAD

**Issue by rissson** [domainelibre/YunohostDockerImage#6]
Hi,

When running the yunohost container (AMD64, latest), my host's hostname changes. The MOTD changes too, and I can't login via the console anymore. However, I can connect to the host through SSH. It probably has to do with the fact that my container is run with `--privileged`. Is there a list of needed capacities, so I can give the container only those needed, and prevent it to mess with my host.
Docker version 18.09.7, build 2d0083d657f82c47044c8d3948ba434b622fe2fd
Host : NixOS 19.03, on a VPS

**Comment by rissson** [comment]
Capacities `NET_ADMIN` and `SYS_ADMIN` seem to be needed. But with those two only, I get errors with slapd no starting.

**Comment by aymhce** [comment]
@rissson Yes, after test, I confirme this issue on principal linux console. On SSH console, no problem. Also, there is a link with slapd and --privileged mode !(?). Slapd won't start without it.
